jinja2_transforms:
  - name: my-jinja2-transform
    description: "short description"
    query: "tags_query"
    template_path: "tags_tpl.j2"

queries:
  - name: tags_query
    file_path: "tags_query.gql"
